services:

  db:
    image: postgres:17.4-bullseye
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d
      - ./postgres_data:/postgres_data
    env_file:
      - ./env_vars/postgres.env
    networks:
      - rootslife
  
  backend:
    build:
      context: ./backend 
    ports:
      - "5000:5000"
    env_file:
      - ./env_vars/postgres.env
    volumes:
      - ./backend:/app
    networks:
      - rootslife
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    networks:
      - rootslife
    volumes:
      - ./frontend:/app
      - /app/node_modules
      
  

networks:
  rootslife:
    driver: bridge
