name: rootslife-app
services:
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    networks:
      - rootslife-app

  api:
    build:
      context: ./server
      target: development
    restart: unless-stopped
    env_file: ./server/.env
    volumes:
      - ./server:/app
      - ./server/node_modules:/app/node_modules
    ports:
      - "5000:5000"
    links:
      - db:db
    networks:
      - rootslife-app
    depends_on:
      - db

  frontend:
    build:
      context: ./client
      target: development
      args:
        VITE_API_URL: http://localhost:3000
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - ./client/node_modules:/app/node_modules
    networks:
      - rootslife-app
    command: npm run dev -- --host 0.0.0.0
    depends_on:
      - api

  caddy:
    image: caddy:2-alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./caddy/Caddyfile.dev:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - rootslife-app
    depends_on:
      - api
      - frontend

volumes:
  postgres_data:
  caddy_data:
  caddy_config:
networks:
  rootslife-app:
    driver: bridge
