name: rootslife-app
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_PASSWORD:${POSTGRES_PASSWORD}
      - POSTGRES_USER:${POSTGRES_USER}
      - POSTGRES_DB:${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    networks:
      - rootslife-app

  api:
    build:
      context: ./server
      target: production
    restart: always
    env_file: ./server/.env
    environment:
      - POSTGRES_PASSWORD:${POSTGRES_PASSWORD}
      - POSTGRES_USER:${POSTGRES_USER}
      - POSTGRES_DB:${POSTGRES_DB}
    volumes:
      - ./server:/app
      - /server/node_modules:/app/node_modules
    ports:
      - "5000:5000"
    networks:
      - rootslife-app
    depends_on:
      - db

  frontend:
    build:
      context: ./client
      target: production
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - ./client/node_modules:/app/node_modules
    networks:
      - rootslife-app
    command: caddy run --config /etc/caddy/Caddyfile
    depends_on:
      - api

  caddy:
    image: caddy:2-apine
    build:
      context: ./caddy
      dockerfile: Dockerfile
    ports:
      - 80:80
      - 443:443
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}
      - ./caddy/Caddyfile.prod:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - rootslife-app
    depends_on:
      - api
      - frontend

volumes:
  postgres_data:
  caddy_data:
  caddy_config:
networks:
  rootslife-app:
    driver: bridge
