services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD:${POSTGRES_PASSWORD}
      - POSTGRES_USER:${POSTGRES_USER}
      - POSTGRES_DB:${POSTGRES_DB}
    healthcheck:
      test: pg_isready -U admin -d rootslife_db
      interval: 5s
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  webserver:
    build: server
    environment:
      - POSTGRES_PASSWORD:${POSTGRES_PASSWORD}
      - POSTGRES_USER:${POSTGRES_USER}
      - POSTGRES_DB:${POSTGRES_DB}
    env_file:
      - .env
    volumes:
      - ./server:/app
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
