"""removal of name on users in favour of email, lastName, firstName

Revision ID: d66baecc91c6
Revises: 44ba87ffd29e
Create Date: 2025-02-25 16:28:20.900463

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd66baecc91c6'
down_revision = '44ba87ffd29e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('firstName', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('lastName', sa.String(length=120), nullable=False))
        batch_op.drop_constraint('user_name_key1', type_='unique')
        batch_op.create_unique_constraint(None, ['firstName'])
        batch_op.create_unique_constraint(None, ['lastName'])
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint('user_name_key1', ['name'])
        batch_op.drop_column('lastName')
        batch_op.drop_column('firstName')

    # ### end Alembic commands ###
