"""removal of name on users in favour of email, lastName, firstName

Revision ID: 5cac10d4a297
Revises: d66baecc91c6
Create Date: 2025-02-25 16:42:57.710794

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5cac10d4a297'
down_revision = 'd66baecc91c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lastName', sa.String(length=120), nullable=False))
        batch_op.alter_column('firstName',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.create_unique_constraint(None, ['lastName'])
        batch_op.create_unique_constraint(None, ['firstName'])
        batch_op.drop_column('last_name')
        batch_op.drop_column('first_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('last_name', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('firstName',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.drop_column('lastName')

    # ### end Alembic commands ###
