"""empty message

Revision ID: 6b15220416e1
Revises: eec5a0444e10
Create Date: 2025-02-27 13:23:29.629158

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b15220416e1'
down_revision = 'eec5a0444e10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('users_first_name_key', type_='unique')
        batch_op.drop_constraint('users_last_name_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_unique_constraint('users_last_name_key', ['last_name'])
        batch_op.create_unique_constraint('users_first_name_key', ['first_name'])

    # ### end Alembic commands ###
